# Generated by Django 6.0.5 on 2026-05-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='doc',
            field=models.FileField(default='name', upload_to='books'),
            preserve_default=False,
        ),
    ]
