# Generated by Django 6.0.5 on 2026-06-04 16:05

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_book_author_book_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='doc',
            field=models.FileField(upload_to=api.models.book_file_path),
        ),
        migrations.CreateModel(
            name='ScheduledJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('UNKNOWN', 'UNKNOWN'), ('SCHEDULED', 'SCHEDULED'), ('SENDING', 'SENDING'), ('CANCELLED', 'CANCELLED'), ('FINISHED', 'FINISHED')], max_length=10)),
                ('sendAt', models.DateTimeField()),
                ('time', models.CharField(max_length=5)),
                ('frequency', models.CharField(max_length=15)),
                ('timezone', models.CharField(max_length=50)),
                ('user_id', models.IntegerField()),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.book')),
            ],
        ),
    ]
